// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebxrmkCN8Z1zaEcnVimGl6DxR7YuFSFc',
    appId: '1:31324009572:android:4e4a905730bbb3fb06db71',
    messagingSenderId: '31324009572',
    projectId: 'natural-1f9b8',
    databaseURL: 'https://natural-1f9b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natural-1f9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1nAS6CXsRiMSSW2SEk_pjs2GJoFBk7U',
    appId: '1:31324009572:ios:fca9270f9d2ba62606db71',
    messagingSenderId: '31324009572',
    projectId: 'natural-1f9b8',
    databaseURL: 'https://natural-1f9b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natural-1f9b8.firebasestorage.app',
    androidClientId: '31324009572-vchqruqa94lvicpr60k086u70pm5u4gn.apps.googleusercontent.com',
    iosClientId: '31324009572-misuiodqpnjmvpg2fe9fpdous0qeu2gs.apps.googleusercontent.com',
    iosBundleId: 'com.shashank.quickmart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9Ld4Z-tNw5mwtuzBZwvG6FpbmTibJAs',
    appId: '1:31324009572:web:e5ddca7f71cd57a406db71',
    messagingSenderId: '31324009572',
    projectId: 'natural-1f9b8',
    authDomain: 'natural-1f9b8.firebaseapp.com',
    databaseURL: 'https://natural-1f9b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natural-1f9b8.firebasestorage.app',
    measurementId: 'G-MBVX2E1S5C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1nAS6CXsRiMSSW2SEk_pjs2GJoFBk7U',
    appId: '1:31324009572:ios:4bf729367cb39a6c06db71',
    messagingSenderId: '31324009572',
    projectId: 'natural-1f9b8',
    databaseURL: 'https://natural-1f9b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natural-1f9b8.firebasestorage.app',
    androidClientId: '31324009572-vchqruqa94lvicpr60k086u70pm5u4gn.apps.googleusercontent.com',
    iosClientId: '31324009572-dj4aj9g6smcve6j8v2ipbsbot6clkrb3.apps.googleusercontent.com',
    iosBundleId: 'com.shashank.quickMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9Ld4Z-tNw5mwtuzBZwvG6FpbmTibJAs',
    appId: '1:31324009572:web:19f7e0591288da1b06db71',
    messagingSenderId: '31324009572',
    projectId: 'natural-1f9b8',
    authDomain: 'natural-1f9b8.firebaseapp.com',
    databaseURL: 'https://natural-1f9b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'natural-1f9b8.firebasestorage.app',
    measurementId: 'G-HR6X17LQC8',
  );

}